cn:
    description: "User name"
    display_name: "User name"
    type: string
    weight: 10
    backends:
        ldap: cn

first-name:
    description: "First name"
    display_name: "First Name"
    type: string
    weight: 20
    backends:
        ldap: givenName

name:
    description: "Last name"
    display_name: "Last name"
    search_displayed: True
    weight: 30
    type: string
    backends:
        ldap: sn

email:
    description: "Email"
    display_name: "Email"
    type: email
    weight: 40
    backends:
        ldap: mail

uid:
    description: "UID"
    display_name: "UID"
    key: True
    type: string
    weight: 50
    autofill: 
        function: lcUid
        args:
            - $first-name
            - $name
            - '10000'
            - '40000'
    backends:
        ldap: uid

password:
    description: "Password"
    display_name: "Password"
    weight: 31
    self: True
    type: password
    backends:
        ldap: userPassword
